[package]
name = "bevy_editor_pls_default_windows"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true

[features]
bevy_metrics_dashboard = ["dep:bevy_metrics_dashboard"]
default = [ "bevy_metrics_dashboard" ]

[dependencies]
bevy = { version = "0.16.0", default-features = false, features = [
    "bevy_scene",
    "bevy_text",
    "bevy_ui",
    "bevy_sprite",
    "bevy_pbr",
    "bevy_core_pipeline",
    "bevy_gizmos",
] }
bevy_metrics_dashboard = { workspace = true, optional = true }
bevy_editor_pls_core.workspace = true
bevy-inspector-egui.workspace = true
bevy_egui.workspace = true
indexmap = "2"
pretty-type-name = "1.0"
bevy_mod_debugdump = "0.13.0"
opener = "0.8.1"
transform-gizmo-bevy.workspace = true
egui_graphs = "0.25.1"
petgraph = { version = "0.8.1", features = ["generate", "dot_parser"] }
dot-parser = "*"
parking_lot = "*"
dirs = "*"
tracing-log = "*"
tracing-error = "*"
# tracing-tracy = "*"
tracing-core = { version = "*", features = ["valuable"]}
egui_extras = "0.31.1"
valuable = "*"
regex = "*"
avian3d = "*" # todo optional dep?
bevy_mod_outline = "*"
smallvec = "1.15.1"
regex_static = "0.1.1"
derive-cmp-ops = "0.1.0"
# cargo patch should disregard semver
# obviously
# bastards

# petgraph.workspace = true
# dot-parser.workspace = true
# dot-parser-macros.workspace = true

[target.wasm32-unknown-unknown.dependencies]
tracing-wasm = "*"
